android {


    signingConfigs {


        release {


            storeFile file("__KEYSTORE_FILE__")


            storePassword "__KEYSTORE_PASSWORD__"


            keyAlias "__KEY_ALIAS__"


            keyPassword "__KEY_PASSWORD__"


        }


    }


    buildTypes {


        release {


            signingConfig signingConfigs.release


        }


    }


}